-- Create extension for vector operations
CREATE EXTENSION IF NOT EXISTS vector;

-- Main Chat Table
CREATE TABLE public.chat
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    title      VARCHAR(255)
);

ALTER TABLE public.chat OWNER TO postgres;

-- Chat Entries Table
CREATE TABLE public.chat_entry
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    TEXT,
    created_at TIMESTAMP(6),
    chat_id    BIGINT
               CONSTRAINT chat_entry_chat_fk
               REFERENCES public.chat(id),
    role       VARCHAR(255)
               CONSTRAINT chat_entry_role_check
               CHECK (role::TEXT = ANY (ARRAY['USER':: VARCHAR, 'ASSISTANT':: VARCHAR]::TEXT[]))
);

ALTER TABLE public.chat_entry OWNER TO postgres;

-- ============================================
-- RAG (Retrieval-Augmented Generation) Tables
-- ============================================

-- Table of loaded documents
CREATE TABLE IF NOT EXISTS loaded_document
(
    id SERIAL PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    document_type VARCHAR(10) NOT NULL,
    chunk_count INTEGER,
    loaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_document UNIQUE(filename,content_hash)
);

-- Index to speed up filename lookups
CREATE INDEX IF NOT EXISTS idx_loaded_documents_filename
    ON loaded_document(filename);

-- Vector Store Table
CREATE TABLE IF NOT EXISTS vector_store
(
    id VARCHAR(255) PRIMARY KEY,
    content TEXT,
    metadata JSON,
    embedding VECTOR(1024)
);

-- HNSW Index for fast vector search
CREATE INDEX IF NOT EXISTS vector_store_hnsw_index
    ON vector_store USING hnsw (embedding vector_cosine_ops);

-- ============================================
-- Notes on index types:
-- HNSW - High-performance similarity search on high-dimensional vectors
-- IVFFlat - Inverted File with flat clusters, good for large datasets
-- No index - Sequential scan over all vectors (slow but exact)
-- ============================================
